{
  "hash": "1dc6b9258ec35452f616bba1dfed41d2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: In-Hospital Cardiac Events and Cost Based on Simulated Data \nauthor:\n  - name: Simeng Wang\n    corresponding: true\n    email: simeng@stanford.edu\n    roles:\n      - Investigation\n      - Visualization\n      - Manuscript preparation and review \n    affiliations:\n      - Stanford University School of Medicine\nkeywords:\n  - cardiac events\n  - hospitalization cost \nabstract: |\n  Certain cardiovascular risk factors have long been defined. It is unclear whether having those risk factors can predispose patients to in-hospital cardiac events, which can also be exacerbated due to acute illness, medication use, and stress from interventions. In this study, 5000 patients from a simulated cohort dataset were retrospectively examined. Smoking status and male sex were found to be significant risk factors for in-hospital cardiac events. Age was not a significant risk factor when other variables were controlled. Patients who had cardiac events during the hospitalization incurred higher cost that those who did not. The study pointed towards a direction of potentially lowering hospitalization cost by optimizing patients' cardiovascular risk factors. \n  \ndate: last-modified\nbibliography: references.bib\n---\n\n## Introduction\nCardiovascular diseases, which include coronary heart disease, peripheral artery disease, and stroke, are common worldwide. They were estimated to have resulted in more than 17 million deaths on an annual basis from 2012 to 2013 [@Laslett2012-ja]. Atherosclerosis, a process in which plaques are developed within the vascular wall and culminate in thromboembolism, is responsible for many cardiovascular diseases according to a study by @Falk2006-tq. There are several established risk factors for atherosclerosis and they often act in concert to increase the overall risks. Atherosclerosis tends to develop with age due to repeated endothelial injury that can result in intimal plaque built-up [@Falk2006-tq]. Men were found to be at three times higher risks than women in a Finnish longitudinal population study [@Jousilahti1999-ar]. Smoking is a well-known risk factor for cardiovascular disease and smoking cessation has been demonstrated to contribute to decreased prevalence of sudden myocardial infarction [@Ambrose2004-qs]. However, it is less clear whether these risk factors also contribute to risks for in-hospital cardiac events when patients were admitted for other illnesses. \n\nIn-hospital cardiac events can lead to increased morbidity and mortality [@Ramadan2022-kq]. They can additionally result in significant cost associated with the hospitalization, which add to the cost to healthcare system and exacerbate financial toxicity for patients [@Kwok2021-gf]. In this study, we used a simulated datatset to establish a prediction model for in-hospital cardiac events using multiple known risk factors cardiovascular diseases, seeking to characterize cost difference among patients who did or did not have cardiac events and propose modifiable factors to minimize cardiac events occurrence and associated cost. \n\n## Data & Methods \n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary (tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary (here)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nhere() starts at /Users/simeng/Library/Mobile Documents/com~apple~CloudDocs/Documents/Grad School/HRP 203/Assignment 4 New/HRP203Assignment4\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncohort_df = read.csv(here::here(\"raw_data\",\"cohort.csv\")) # load dataset using a relative path \nid_count <- nrow (cohort_df) # count of patients in the dataset \nvar_count <- ncol (cohort_df) # count of variables in the dataset \n```\n:::\n\n\n\nThis study was conducted using a cohort simulated data for the course HRP 203 at Stanford University during the spring quarter of 2024-2025 academic year. The data contained 5000 individual patients. Data of 5 variables were collected for each patient, including their smoking status, sex, age, whether they had a cardiac event during the hospitalization, and the cost of the hospitalization. \n\nStatistical analyses were performed using R version 4.4.2 (2024-10-31) and the manuscript was prepared using the Quarto®. Data summary was performed by counting the percentage of an event or averaging the statistics of a numeric variable. Figures were constructed using the ggplot2 package in R. A logistic regression model was constructed to look for statistically significant predictors of cardiac events during the hospitalization. The regression formula is shown below, where $Y_c$ denotes cardiac events, $\\beta_0$ denotes intercept, and $\\varepsilon_i$ denotes random error term. \n\n$$\nY_c =  \\beta_0+ \\beta_1*smoke+\\beta_2*female+\\beta_3*age+\\varepsilon_i\n$$ \n\nI attest that I did not use generative artificial intelligence technology to complete any portion of the work.\n\n## Results\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\nlibrary(knitr)\n\n# Calculate the summary statistics for Table 1 \ntable1 <- cohort_df %>% \n  summarize(\n    `Total Number of Patient` = nrow (cohort_df),\n    `Percent Female` = mean(female, na.rm = TRUE)*100, \n    `Percent Smokers` = mean(smoke, na.rm = TRUE)*100, \n    `Average Age` = mean(age, na.rm = TRUE), \n    `Percent Cardiac Event` = mean(cardiac, na.rm = TRUE)*100, \n    `Average Cost` = mean(cost, na.rm = TRUE)\n  ) %>% \n  t() %>% \n  as.data.frame()\n\n#Create Table 1 \ncolnames(table1) <- \"Value\"\ntable1$Value <- round(table1$Value, 0)  #round to 1 decimal place \ntable1$Variable <- rownames(table1)\nrownames(table1) <- NULL\ntable1 <- table1[, c(\"Variable\", \"Value\")]\n\n#Print Table 1 \nkable(table1, caption = \"Table 1. Summary Statistics of the Cohort\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in attr(x, \"align\"): 'xfun::attr()' is deprecated.\nUse 'xfun::attr2()' instead.\nSee help(\"Deprecated\")\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in attr(x, \"format\"): 'xfun::attr()' is deprecated.\nUse 'xfun::attr2()' instead.\nSee help(\"Deprecated\")\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Table 1. Summary Statistics of the Cohort\n\n|Variable                | Value|\n|:-----------------------|-----:|\n|Total Number of Patient |  5000|\n|Percent Female          |    55|\n|Percent Smokers         |    16|\n|Average Age             |    44|\n|Percent Cardiac Event   |     5|\n|Average Cost            |  9166|\n\n\n:::\n:::\n\nTable 1 summarizes the statistics in this dataset. Among the 5000 patients, 55% were female, 16% were smokers, and 5% had a cardiac event during the hospitalization. The average age of the cohort was 44 years. The average cost of the hospitalization was 9166 dollars. \n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\nlibrary(ggplot2)\n\n# Construct dataset for Figure 1\n# Group patients into different age groups, separated by 10 years apart \n# Subdivide by sex \nfigure1 <- cohort_df %>% \n  mutate(\n    age_group = cut(age, breaks = seq (15, 75, by = 10)),\n    sex = factor(female, levels = c(1,0), labels =c(\"Female\", false=\"Male\"))\n) %>% \n  group_by(age_group, sex) %>% \n  summarize(\n    n= n(),\n    event_rate = mean(cardiac, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>% \n  filter(!is.na(age_group), !is.na(sex))\n                    \n#Plot \nggplot(figure1,\n       aes(x = age_group, y = event_rate, color = sex, group = sex)) +\n  geom_line (linewidth = 1.2) +\n  geom_point (size = 3) +\n  scale_y_continuous(labels = scales ::percent_format()) + \n  labs(\n    title = \"Figure 1. Cardiac Event Rate by Age Group, Male vs. Female\",\n    x = \"Age Group\",\n    y = \"Cardiac Event Rate\",\n    color = \"Sex\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/figure1-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\nlibrary(ggplot2)\n\n# Construct dataset for Figure 2\n# Group patients into different age groups, separated by 10 years apart \n# Subdivide by smoking status \nfigure2 <- cohort_df %>% \n  mutate(\n    age_group = cut(age, breaks = seq (15, 75, by = 10)),\n    smoking_status = factor(smoke, levels = c(1,0), labels =c(\"Smokers\", \"Non-Smokers\")), \n) %>% \n  group_by(age_group, smoking_status) %>% \n  summarize(\n    n= n(),\n    event_rate = mean(cardiac, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>% \n  filter(!is.na(age_group), !is.na(smoking_status))\n                    \n#Plot \nggplot(figure2,\n       aes(x = age_group, y = event_rate, color = smoking_status, group = smoking_status)) +\n  scale_color_manual(values = c(\"Smokers\" = \"orange\", \"Non-Smokers\" = \"green\")) + #Selected new colors for this lineplot \n  geom_line (linewidth = 1.2) +\n  geom_point (size = 3) +\n  scale_y_continuous(labels = scales ::percent_format()) + \n  labs(\n    title = \"Figure 2. Cardiac Event Rate by Age Group, Smokers vs. Non-Smokers\",\n    x = \"Age Group\",\n    y = \"Cardiac Event Rate\",\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/figure2-1.png){width=672}\n:::\n:::\n\nFigure 1 and Figure 2 demonstrate the cardiac events rate among this patient cohort. It was evident that there was a trend of increasing cardiac event rate by patient's age. The cardiac event rate was higher among male patients than female patients across all age groups; similarly, higher among smokers than non-smokers. The highest cardiac event rate was found among patients who were smokers between 65 and 75 years of age, which was 28.1%.\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\nlibrary(broom)\nlibrary(knitr)\n\n# Fit linear regression model \nlr <- glm(cardiac ~ smoke + female + age, data = cohort_df, family=\"binomial\")\n\n# Extract odds ratio and 95% confidence interval and summarize results with broom package \nlr_table <- tidy(lr, exponentiate = TRUE, conf.int = TRUE) %>% \n  filter(term != \"(Intercept)\") %>%  #remove the intercept row \n  select(term, estimate, conf.low, conf.high, p.value) %>%   #calculate odds ratio and confidence interval \n  rename(\n    Term = term,\n    OR = estimate,  \n    \"CI Lower\" = conf.low,\n    \"CI Upper\" = conf.high,\n    \"P-value\" = p.value\n  ) %>% \n  mutate(\n    OR = round(OR, 2),   #rounding \n    `CI Lower` = round(`CI Lower`, 2),\n    `CI Upper` = round(`CI Upper`, 2),\n    `P-value` = signif(`P-value`, 1)\n  ) \n\n#Print result table \nknitr::kable(lr_table, caption = \"Table 2. Linear Regression Predicting Hospital Cardiac Event\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in attr(x, \"align\"): 'xfun::attr()' is deprecated.\nUse 'xfun::attr2()' instead.\nSee help(\"Deprecated\")\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in attr(x, \"format\"): 'xfun::attr()' is deprecated.\nUse 'xfun::attr2()' instead.\nSee help(\"Deprecated\")\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Table 2. Linear Regression Predicting Hospital Cardiac Event\n\n|Term   |   OR| CI Lower| CI Upper| P-value|\n|:------|----:|--------:|--------:|-------:|\n|smoke  | 8.26|     6.27|    10.91|    0.00|\n|female | 0.08|     0.06|     0.12|    0.00|\n|age    | 1.01|     1.00|     1.02|    0.08|\n\n\n:::\n:::\n\nThe result of the linear regression model was shown in Table 2. Smoking status and sex of the patient were significantly associated with cardiac events. The odds of smokers were 8.26 times of that of nonsmokers (95% confidence interval, CI, 6.27-10.91). Odds of female were 0.08 of that of male, which was equivalent to the odds of male being 12.5 of that of female for developing cardiac events (95% CI, 8.33-16.67). Age had a positive association with developing a cardiac event, but it did not achieve statistical significance when other variables were controlled for. \n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(tidyr)\nlibrary(dplyr)\nlibrary(ggplot2)\n\n# Construct dataset for Figure 3\nfigure3 <- cohort_df %>% \n  mutate(\n    Smoking_Status = factor(smoke, levels = c(1,0), labels =c(\"Smokers\", \"Non-Smokers\")), \n    Sex = factor(female, levels = c(1,0), labels =c(\"Female\", false=\"Male\")),\n    Cardiac_Event= factor(cardiac, levels = c(1,0), labels = c(\"Event\", \"No Event\"))\n) %>% \npivot_longer(\n  cols = c(Smoking_Status, Sex, Cardiac_Event),\n  names_to = \"Group\",\n  values_to = \"Category\"\n) %>% \n  mutate(fillcolor = Group)\n        \n\n#define the color of each facet \nfacet_colors <- c(\n  \"Sex\" =\"green\",\n  \"Smoking_status\" = \"grey\",\n  \"Cardiac_Event\" = \"red\"\n)\n\n#Create three different facets (by different variables)\nggplot(\n  figure3, aes(x = Category, y = cost, fill=fillcolor)) + \n  geom_boxplot(outlier.size =0.8) +\n  scale_fill_manual(values = facet_colors) +\n  facet_wrap(~ Group, scales = \"free_x\") +\n  labs(\n    title = \"Figure 3. Hospital Cost Difference by Smoking Status, Sex, and Cardiac Event\",\n    x = \"\", y = \"Cost in Dollar\"\n  ) + \ntheme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/figure3-1.png){width=672}\n:::\n:::\n\nFigure 3 demonstrates the cost differences when the patients in the dataset were grouped by their characteristics. On average, patients who had a cardiac event during the hospitalization had higher cost than those who did not; male patients had higher cost than female patients; and smokers had higher cost than non-smokers.\n\n\n## Discussion\nThis study demonstrated that smoking status and male sex were significant risks factors for in-hospital cardiac events. There was a trend of increased risk with age, although statistical significance was not achieved in the regression model. It proposed a prediction model that can be used to estimate a patient's in-hospital cardiac event risks based on several risk factors. Additionally, the study demonstrated increased cost of hospitalization associated with cardiac events. \n\nThere are several limitation to the study. First, the risk factors for cardiovascular diseases were not all inclusive. Multiple other known factors, such as hypertension and diabetes were missing in the dataset [@Saeedi2019-ba]. Second, there was not adequate granularity in terms of hospitalization characteristics, such as undergoing invasive procedures, use of antiplatelet therapy, or massive volume resuscitation, that could positively or negatively impact risks for cardiac events. Third, the study was modeled on a simulated dataset therefore it is unknown whether it can be generalized to real-life practice. Nevertheless, the study proposed a feasible methodology to establish a prediction model for in-hospital cardiac events. Future directions will focus on collecting multi-center data, expanding variables to enhance the prediction capability of the model, and prospectively validate the model. The ultimate goal of the study will be to help clinicians identify and optimize risks for in-hospital events, which can lead to decreased morbidity, mortality, and cost of hospitalization. \n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}